[package]
name = "rbtc_nodewalker"
version = "0.2.0"
authors = ["q"]
edition = "2018"

[dependencies]
dns-lookup = "1.0.0"
chrono = "0.4.6"
rbtc = { path = "../rbtc" }
rand = "0.6"

[dependencies.rusqlite]
version = "0.16.0"
features = ["bundled"]